spring:
  datasource:
    url: jdbc:mysql://localhost:3306/io_game?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

game:
  port: 6000
  idle:
    reader-idle-time: 120
    writer-idle-time: 900
    all-idle-time: 300
    time-unit: seconds
    pong: true
